### ISSUE TITLE
Add Portfolio/Dashboard Section

### ISSUE THREAD

**Issue by iampavangandhi** [iampavangandhi/TradeByte#12]
**Description**
When a user logins he/she redirected to the portfolio page. following things are shown in the portfolio page
- 1) Favorite stocks section
- 2) Profit/Loss/Current-Balance section (with a button to add balance)
- 3) Owned Stocks section (with the option to view and sell them)

**Suggestions and Tips**
First, use dummy data (lorem ipsum) and design frontend and the routes.

**Additional context**
You have to work on both the frontend and the backend

**Comment by garimasingh22** [comment]
[portfolio_dashboard.zip](https://github.com/iampavangandhi/TradeByte/files/5043251/portfolio_dashboard.zip)

**Comment by garimasingh22** [comment]
tailwind css used

**Comment by iampavangandhi** [comment]
Issues Resolved By @fabcodingzest and @garimasingh22
