### ISSUE TITLE
Remove Unaccessable Stock Symbols from the data-total.json

### ISSUE THREAD

**Issue by iampavangandhi** [iampavangandhi/TradeByte#67]
**Description**
Remove Unaccessable Stock Symbols from the data-total.json

**Suggestions and Tips**
Tip: use setInterval or setTimeout methods to avoid API limit exceeded the issue

**Additional context**
Create your own alpha vantage API keys for that.

**Comment by garimasingh22** [comment]
datacompact maine manually check kia th so usme jo AUXL krke jo stock h jo
hi sirf 404 de ra th baki sab render krre th
you can use that as reference
